### PR TITLE
win-devel warning/notes

### PR DESCRIPTION
**Pull request by skeydan**

### CODE REVIEW

**Comment by skeydan** [comment]
Will try to fix the workflow tomorrow.

Regarding win-devel, with these changes the warning is gone, but they dislike "pre-processing" just as much as "preprocessing" ;-)) ... c'est la vie.

```
* using log directory 'd:/RCompile/CRANguest/R-devel/torchaudio.Rcheck'
* using R Under development (unstable) (2022-12-20 r83482 ucrt)
* using platform: x86_64-w64-mingw32 (64-bit)
* using session charset: UTF-8
* using C++ compiler: 'Error in system2(cxx, "--version", TRUE, TRUE) : 
  '"$(BINPREF)g++"' not found
'
* checking for file 'torchaudio/DESCRIPTION' ... OK
* this is package 'torchaudio' version '0.2.1'
* package encoding: UTF-8
* checking CRAN incoming feasibility ... [14s] NOTE
Maintainer: 'Athos Damiani <zkajdan@proton.me>'

New submission

Package was archived on CRAN

Possibly misspelled words in DESCRIPTION:
  pre (6:54)

CRAN repository db overrides:
  X-CRAN-Comment: Archived on 2022-08-08 as issues were not corrected
    in time.
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking serialization versions ... OK
* checking whether package 'torchaudio' can be installed ... OK
* checking installed package size ... OK
* checking package directory ... OK
* checking for future file timestamps ... OK
* checking 'build' directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... [1s] OK
* checking whether the package can be loaded with stated dependencies ... [1s] OK
* checking whether the package can be unloaded cleanly ... [1s] OK
* checking whether the namespace can be loaded with stated dependencies ... [1s] OK
* checking whether the namespace can be unloaded cleanly ... [1s] OK
* checking loading without being on the library search path ... [1s] OK
* checking use of S3 registration ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... [18s] OK
* checking Rd files ... [2s] OK
* checking Rd metadata ... OK
* checking Rd line widths ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking line endings in C/C++/Fortran sources/headers ... OK
* checking pragmas in C/C++ headers and code ... OK
* checking compiled code ... OK
* checking installed files from 'inst/doc' ... OK
* checking files in 'vignettes' ... OK
* checking examples ... [3s] OK
* checking for unstated dependencies in 'tests' ... OK
* checking tests ... [1s] OK
  Running 'testthat.R' [1s]
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes in 'inst/doc' ... OK
* checking re-building of vignette outputs ... [3s] OK
* checking PDF version of manual ... [29s] OK
* checking HTML version of manual ... [16s] OK
* checking for detritus in the temp directory ... OK
* DONE
Status: 1 NOTE
```

**Comment by dfalbel** [comment]
Yeah, the misspelling won't be a problem when submitting.

**Comment by skeydan** [comment]
hm, it does find `g++` though, as seen in the `install.log`:

```
* installing *source* package 'torchaudio' ...
** using staged installation
** libs
g++ -std=gnu++11  -I"D:/RCompile/recent/R/include" -DNDEBUG  -I'D:/RCompile/CRANpkg/lib/4.3/Rcpp/include'   -I"d:/rtools42/x86_64-w64-mingw32.static.posix/include"     -pedantic -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c RcppExports.cpp -o RcppExports.o
g++ -std=gnu++11  -I"D:/RCompile/recent/R/include" -DNDEBUG  -I'D:/RCompile/CRANpkg/lib/4.3/Rcpp/include'   -I"d:/rtools42/x86_64-w64-mingw32.static.posix/include"     -pedantic -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c read_mp3.cpp -o read_mp3.o
g++ -std=gnu++11  -I"D:/RCompile/recent/R/include" -DNDEBUG  -I'D:/RCompile/CRANpkg/lib/4.3/Rcpp/include'   -I"d:/rtools42/x86_64-w64-mingw32.static.posix/include"     -pedantic -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c read_wav.cpp -o read_wav.o
In file included from read_wav.cpp:2:
AudioFile.h: In instantiation of 'bool AudioFile<T>::decodeWaveFile(std::vector<unsigned char>&) [with T = float]':
AudioFile.h:486:16:   required from 'bool AudioFile<T>::load(std::string) [with T = float; std::string = std::__cxx11::basic_string<char>]'
read_wav.cpp:9:28:   required from here
AudioFile.h:617:59: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
  617 |                     sample = (T)reinterpret_cast<float&> (sampleAsInt);
      |                                                           ^~~~~~~~~~~
AudioFile.h: In instantiation of 'bool AudioFile<T>::decodeAiffFile(std::vector<unsigned char>&) [with T = float]':
AudioFile.h:490:16:   required from 'bool AudioFile<T>::load(std::string) [with T = float; std::string = std::__cxx11::basic_string<char>]'
read_wav.cpp:9:28:   required from here
AudioFile.h:762:59: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
  762 |                     sample = (T)reinterpret_cast<float&> (sampleAsInt);
      |                                                           ^~~~~~~~~~~
g++ -std=gnu++11 -shared -s -static-libgcc -o torchaudio.dll tmp.def RcppExports.o read_mp3.o read_wav.o -Ld:/rtools42/x86_64-w64-mingw32.static.posix/lib/x64 -Ld:/rtools42/x86_64-w64-mingw32.static.posix/lib -LD:/RCompile/recent/R/bin/x64 -lR
installing to d:/RCompile/CRANguest/R-devel/lib/00LOCK-torchaudio/00new/torchaudio/libs/x64
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* MD5 sums
packaged installation of 'torchaudio' as torchaudio_0.2.1.zip
* DONE (torchaudio)
```

Maybe `$(BINPREF)` is empty, but then `g++` is found in a different way?

I found one issue where someone had the same warning, but it didn't prevent the software from working (stan, in this case): https://github.com/stan-dev/rstan/issues/855#issuecomment-698666099

**Comment by dfalbel** [comment]
@skeydan Can we merge this PR?

**Comment by skeydan** [comment]
please do :-)))

**Pull request merged**
