### PR TITLE
install OS libs before R pkgs

### PR DESCRIPTION
**Pull request by skeydan**

### CODE REVIEW

**Comment by skeydan** [comment]
OK, this seems to have worked, but there are lots of test errors (basically the same on all OSes).

Did those use to work?
See e.g. https://github.com/curso-r/torchaudio/actions/runs/3756345668/jobs/6382317617

Should we fix them before submitting to CRAN (where tests don't run)?

**Comment by dfalbel** [comment]
I think it's important to at least understand why they are failing and remove them if we end up concluding they are not necessary. They might be hiding failures in other parts of the package code.

**Comment by skeydan** [comment]
Makes sense! Will create a separate issue for that, so this can be about the workflow only.

**Comment by skeydan** [comment]
I guess this one could be merged, then? (So PR checks won't fail with this)

**Pull request merged**
